apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigo-service
  labels:
    app: apigo-service
    version: latest
spec:
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: apigo-service
      version: latest
  template:
    metadata:
      labels:
        app: apigo-service
        version: latest
    spec:
      containers:
        - name: apigo-service
          image: asia.gcr.io/jobfinder-362313/apigo-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: apigo-service-env
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 130
            timeoutSeconds: 10
            failureThreshold: 10  
      restartPolicy: Always
      terminationGracePeriodSeconds: 10

